### PR TITLE
fix: close the last window

### PR DESCRIPTION
**Pull request by MengQ0627**

### CODE REVIEW

**Review by hedyhli — APPROVED** [review]
I'm fine with this behavior, but will be open to make this a config option if some people prefer it to close the outline and re-open the code window instead (behavior of nvim-tree).

**Comment by gennaro-tedesco** [comment]
Good morning! After this recent commit I see an error
```
09:02:13 msg_show   q Error executing lua callback: ...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:389: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:389: in function '__goto_location'
	...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:201: in function <...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:198>
   Error  09:02:13 msg_show.lua_error   q Error detected while processing CursorMoved Autocommands for "<buffer=6>":
   Error  09:02:13 msg_show.lua_error   q Error detected while processing CursorMoved Autocommands for "<buffer=6>":
09:02:13 msg_show   q Error executing lua callback: ...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:389: Invalid window id: 1000
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:389: in function '__goto_location'
	...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:201: in function <...cal/share/nvim/lazy/outline.nvim/lua/outline/sidebar.lua:198>
```
when closing `:q` a window (generally the main buffer window) while outline is open.

**Comment by hedyhli** [comment]
Ah, looks like `auto_jump` is attempting to go to the code buffer location when the code buffer is already closed. I'll look into it.

**Comment by gennaro-tedesco** [comment]
Thank you for looking into it so quickly!

What is the expected behaviour of this feature, however? I still see the outline window open when the last window is closed (or the buffer deleted).

**Comment by hedyhli** [comment]
Nope, it doesn't do anything when the code window closes. This PR allows the outline as the last window to be closed (as if with `:q`) when you press `q` to close the outline - it previously produced an error.

The use case is when you want to quit neovim with `:[w]q`, but forgot to use `:[w]qa` since the outline window is also open (see #86).

**Pull request merged**
